In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('call_activity.csv')
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [4]:
df.iloc[14]

State                        IA
Account length               62
Area code                   415
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes           NaN
Total day calls             NaN
Total day charge            NaN
Total eve minutes         307.2
Total eve calls            76.0
Total eve charge          26.11
Total night minutes       203.0
Total night calls          99.0
Total night charge         9.14
Total intl minutes         13.1
Total intl calls              6
Total intl charge          3.54
Customer service calls      4.0
Churn                     False
Name: 14, dtype: object

In [5]:
df.iloc[14, 1]

np.int64(62)

Slicing

In [6]:
df.iloc[14:24]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False
19,TX,73,415,No,No,0,NaN,NaN,NaN,NaN,88.0,13.56,192.8,74.0,8.68,13.0,2,3.51,1.0,False
20,FL,147,415,No,No,0,NaN,NaN,NaN,239.7,93.0,20.37,208.8,133.0,9.40,10.6,4,2.86,0.0,False
21,CO,77,408,No,No,0,NaN,NaN,NaN,169.9,121.0,14.44,209.6,64.0,9.43,5.7,6,1.54,5.0,True
22,AZ,130,415,No,No,0,183.0,112.0,31.11,72.9,99.0,6.20,181.8,78.0,8.18,9.5,19,2.57,0.0,NaN
23,SC,111,415,No,No,0,110.4,103.0,18.77,137.3,102.0,11.67,189.6,105.0,8.53,7.7,6,2.08,2.0,False